### ISSUE TITLE
Documentation or quickstart

### ISSUE THREAD

**Issue by KodeMunkie** [YRZrandir/OrthoMeshTools#3]
I appreciate this is a new project so doesn't yet have documentation, but I have nowhere to start and would like to use this on the command line for fixing some stl, obj and ply files.

Could you update the readme with a quick start or add some other documentation please with examples for the above case?

**Comment by YRZrandir** [comment]
Added documentation about the MeshFix program. The program is still in development and has been changing a lot. I will try to keep the documentation up to date.
